// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/imgpoto/img.proto

package go_micro_srv_user_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Uuid                 int64    `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0afd9cd71c1027, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

type Response struct {
	Msg                  string          `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Pix                  []byte          `protobuf:"bytes,2,opt,name=pix,proto3" json:"pix,omitempty"`
	Stride               int64           `protobuf:"varint,3,opt,name=stride,proto3" json:"stride,omitempty"`
	Min                  *Response_Point `protobuf:"bytes,4,opt,name=min,proto3" json:"min,omitempty"`
	Man                  *Response_Point `protobuf:"bytes,5,opt,name=man,proto3" json:"man,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0afd9cd71c1027, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMan() *Response_Point {
	if m != nil {
		return m.Man
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0afd9cd71c1027, []int{1, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.user_server.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user_server.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.user_server.Response.Point")
}

func init() { proto.RegisterFile("proto/imgpoto/img.proto", fileDescriptor_ee0afd9cd71c1027) }

var fileDescriptor_ee0afd9cd71c1027 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0xc4, 0x38, 0x2d, 0xf0, 0xe8, 0x80, 0xde, 0x00, 0x56, 0x25, 0xa4, 0x10, 0x96, 0x4c, 0x46,
	0x2a, 0x1b, 0x2b, 0x13, 0x13, 0xc8, 0x03, 0x2b, 0x0a, 0xd4, 0x8a, 0x2c, 0xd5, 0x76, 0xf0, 0x4b,
	0xaa, 0xe4, 0x7b, 0xf9, 0x11, 0xe4, 0xa7, 0x30, 0x02, 0xea, 0xe4, 0xbb, 0xb3, 0xce, 0x77, 0x3e,
	0xb8, 0xea, 0x52, 0xec, 0xe3, 0x9d, 0xf3, 0x6d, 0x37, 0x9f, 0x9a, 0x15, 0x54, 0x6d, 0xd4, 0xde,
	0x7d, 0xa4, 0xa8, 0x29, 0xed, 0xf5, 0x40, 0x36, 0xbd, 0x91, 0x4d, 0x7b, 0x9b, 0xaa, 0x6b, 0x38,
	0x31, 0xf6, 0x73, 0xb0, 0xd4, 0x23, 0x42, 0x31, 0x0c, 0x6e, 0xab, 0x44, 0x29, 0x6a, 0x69, 0x18,
	0x57, 0x5f, 0x02, 0x4e, 0x8d, 0xa5, 0x2e, 0x06, 0xb2, 0x78, 0x01, 0xd2, 0x53, 0xcb, 0xf7, 0x67,
	0x26, 0xc3, 0xac, 0x74, 0x6e, 0x54, 0xc7, 0xa5, 0xa8, 0x57, 0x26, 0x43, 0xbc, 0x84, 0x25, 0xf5,
	0xc9, 0x6d, 0xad, 0x92, 0xfc, 0xcc, 0xcc, 0xf0, 0x01, 0xa4, 0x77, 0x41, 0x15, 0xa5, 0xa8, 0xcf,
	0x37, 0xb5, 0xfe, 0xad, 0x8f, 0xfe, 0x09, 0xd3, 0x2f, 0xd1, 0x85, 0xde, 0x64, 0x13, 0x7b, 0x9b,
	0xa0, 0x16, 0x07, 0x7b, 0x9b, 0xb0, 0xbe, 0x85, 0x05, 0x33, 0x5c, 0x81, 0x18, 0xe7, 0xaf, 0x89,
	0x31, 0xb3, 0x89, 0x6b, 0x4b, 0x23, 0xa6, 0xcd, 0x2b, 0xc8, 0x27, 0xdf, 0xe2, 0x33, 0x14, 0x8f,
	0xcd, 0x6e, 0x87, 0x37, 0x7f, 0x45, 0xf0, 0x56, 0xeb, 0xea, 0xff, 0x16, 0xd5, 0xd1, 0xfb, 0x92,
	0xd7, 0xbf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x78, 0xcb, 0x36, 0xa7, 0x98, 0x01, 0x00, 0x00,
}
