// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/common/common.proto

package go_micro_srv_user_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Common service

type CommonService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type commonService struct {
	c    client.Client
	name string
}

func NewCommonService(name string, c client.Client) CommonService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.user_server"
	}
	return &commonService{
		c:    c,
		name: name,
	}
}

func (c *commonService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Common.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Common service

type CommonHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterCommonHandler(s server.Server, hdlr CommonHandler, opts ...server.HandlerOption) error {
	type common interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Common struct {
		common
	}
	h := &commonHandler{hdlr}
	return s.Handle(s.NewHandler(&Common{h}, opts...))
}

type commonHandler struct {
	CommonHandler
}

func (h *commonHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CommonHandler.Call(ctx, in, out)
}
